### ISSUE TITLE
Command Line closeaftersync and silentmode

### ISSUE THREAD

**Issue by MrBobC** [trakt/Trakt-for-Mediaportal#100]
This does not seem to work.  --sync works, but neither --closeaftersync or --silentmode do any syncing.

**Comment by damienhaynes** [comment]
Show me the exact command line you are using please.

**Comment by MrBobC** [comment]
Oh no, I tried 
--closeaftersync
all by itself.

**Comment by damienhaynes** [comment]
Okay, let me know how it goes when using it together. 

The reason you need both is as I can reserve to include additional options later e.g. change settings silently etc.

**Comment by MrBobC** [comment]
That worked!
