### ISSUE TITLE
Crash on sync

### ISSUE THREAD

**Issue by MrJackJonesIII** [trakt/Trakt-for-Mediaportal#110]
Hi ltfearme,

I had to rebuild my tv-series db last night. I don't know if it is related to the following error cause after the rebuild the sync worked fine and I used MP for some time after that. 
But now MP is crashing after restart and I get this in the error log. 

`[2016-06-01 09:51:50,877] [Error  ] [DashShows] [ERROR] - MediaPortal: Unhandled exception occured
[2016-06-01 09:51:50,883] [Log    ] [DashShows] [ERROR] - Exception: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei TraktPlugin.TraktCache.IsWatched(TraktShowSummary show) in C:\Development\Trakt\TraktPlugin\TraktCache.cs:Zeile 2342.
   bei TraktPlugin.GUI.GUICommon.<FilterTrendingShows>b__5c(TraktShowTrending t) in C:\Development\Trakt\TraktPlugin\GUI\GUICommon.cs:Zeile 3199.
   bei System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   bei System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei TraktPlugin.TraktDashboard.PublishShowProperties(IEnumerable`1 trendingItems) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 794.
   bei TraktPlugin.TraktDashboard.LoadTrendingShows(Boolean forceReload) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 752.
   bei TraktPlugin.TraktDashboard.<Init>b__a3(Object o) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 3256.
   bei System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.TimerQueueTimer.CallCallback()
   bei System.Threading.TimerQueueTimer.Fire()
   bei System.Threading.TimerQueue.FireNextTimers()
   bei System.Threading.TimerQueue.AppDomainTimerCallback()  Message: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.  Site   : Boolean IsWatched(TraktPlugin.TraktAPI.DataStructures.TraktShowSummary)  Source : TraktPlugin  Stack Trace:     bei TraktPlugin.TraktCache.IsWatched(TraktShowSummary show) in C:\Development\Trakt\TraktPlugin\TraktCache.cs:Zeile 2342.
   bei TraktPlugin.GUI.GUICommon.<FilterTrendingShows>b__5c(TraktShowTrending t) in C:\Development\Trakt\TraktPlugin\GUI\GUICommon.cs:Zeile 3199.
   bei System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   bei System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei TraktPlugin.TraktDashboard.PublishShowProperties(IEnumerable`1 trendingItems) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 794.
   bei TraktPlugin.TraktDashboard.LoadTrendingShows(Boolean forceReload) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 752.
   bei TraktPlugin.TraktDashboard.<Init>b__a3(Object o) in C:\Development\Trakt\TraktPlugin\TraktDashboard.cs:Zeile 3256.
   bei System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.TimerQueueTimer.CallCallback()
   bei System.Threading.TimerQueueTimer.Fire()
   bei System.Threading.TimerQueue.FireNextTimers()
   bei System.Threading.TimerQueue.AppDomainTimerCallback()`

I noticed the path C:\Development\Trakt\TraktPlugin\TraktDashboard.cs in the log above. It does not exist on my machine. Don't know if it means anything.
I'll add the usual mp debug logs as well.
[MediaPortalLogs_01_06_16__09_51.zip](https://github.com/trakt/Trakt-for-Mediaportal/files/292890/MediaPortalLogs_01_06_16__09_51.zip)

**Comment by MrJackJonesIII** [comment]
I forgot to mention something: After firing up MP this morning I got an error message there about the trakt login popping up for a second. To fast to read it. Then after some time the first crash happened.

**Comment by damienhaynes** [comment]
This appears to be a API issue. Its returning the incorrect data structures and causes a crash.

It should auto fix itself but I will add some protection in case it happens again in the future.

**Comment by damienhaynes** [comment]
Ive added some more protection to guard again this issue.

**Comment by MrJackJonesIII** [comment]
Thx Damien! Great support as always! 
Luca
